# Generated by Django 6.0.7 on 2026-08-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_entregas_parciales'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=500, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'abonos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=30)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clientes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comisiones',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('base_comision', models.DecimalField(decimal_places=2, max_digits=16)),
                ('valor_comision', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado_pago', models.CharField(max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleOrden',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion_producto', models.CharField(max_length=250)),
                ('cantidad', models.IntegerField()),
                ('cantidad_entregada', models.IntegerField(default=0)),
                ('costo_unitario_dolares', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_unitario_pesos', models.DecimalField(decimal_places=2, max_digits=16)),
                ('precio_venta_unitario', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_costo_pesos', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ganancia_producto', models.DecimalField(decimal_places=2, max_digits=16)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'detalle_orden',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientosDinero',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('tipo_movimiento', models.CharField(max_length=10)),
                ('categoria', models.CharField(max_length=60)),
                ('descripcion', models.TextField()),
                ('valor_moneda_original', models.DecimalField(decimal_places=2, max_digits=16)),
                ('moneda', models.CharField(max_length=3)),
                ('tasa_dolar', models.DecimalField(decimal_places=4, max_digits=12)),
                ('valor_pesos', models.DecimalField(decimal_places=2, max_digits=16)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('comprobante', models.CharField(blank=True, max_length=500, null=True)),
                ('registrado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimientos_dinero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_orden', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateTimeField()),
                ('tasa_dolar', models.DecimalField(decimal_places=4, max_digits=12)),
                ('flete_dolares', models.DecimalField(decimal_places=2, max_digits=14)),
                ('flete_pesos', models.DecimalField(decimal_places=2, max_digits=16)),
                ('subtotal_venta', models.DecimalField(decimal_places=2, max_digits=16)),
                ('costo_productos_pesos', models.DecimalField(decimal_places=2, max_digits=16)),
                ('otros_costos_pesos', models.DecimalField(decimal_places=2, max_digits=16)),
                ('costo_total_pesos', models.DecimalField(decimal_places=2, max_digits=16)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ganancia_bruta', models.DecimalField(decimal_places=2, max_digits=16)),
                ('comision_vendedor', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ganancia_neta', models.DecimalField(decimal_places=2, max_digits=16)),
                ('total_abonado', models.DecimalField(decimal_places=2, max_digits=16)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado', models.CharField(max_length=30)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_inicio', models.SmallIntegerField(blank=True, null=True)),
                ('anio_fin', models.SmallIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad_disponible', models.IntegerField()),
                ('costo_dolares', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_pesos', models.DecimalField(decimal_places=2, max_digits=16)),
                ('precio_venta_sugerido', models.DecimalField(decimal_places=2, max_digits=16)),
                ('estado', models.CharField(max_length=30)),
                ('imagen', models.CharField(blank=True, max_length=500, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_recibo', models.CharField(max_length=30, unique=True)),
                ('fecha_generacion', models.DateTimeField()),
                ('total_recibo', models.DecimalField(decimal_places=2, max_digits=16)),
                ('ruta_pdf', models.CharField(blank=True, max_length=500, null=True)),
                ('generado_por', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recibos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendedores',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'vendedores',
                'managed': False,
            },
        ),
    ]
